# 使用基于 Debian Bullseye 的 Python 3.10 官方镜像
FROM python:3.10-slim-bullseye

# 设置容器中的工作目录
WORKDIR /app

# 复制 requirements.txt 到容器中
COPY ./backend/requirements.txt /app/

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 将其余的应用程序代码复制到容器中
COPY ./backend /app

# 暴露应用运行的端口
EXPOSE 7001

# 运行应用程序的命令
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7001"]
