FROM node:20.9-bullseye-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./frontend /app/

RUN cd /app && yarn install && yarn run build

# Expose port 5173 to access the server
EXPOSE 8080

# Command to run the application
CMD ["npx", "http-server", "/app/build/", "--port", "8080"]