FROM python:3.12-slim-bullseye

ENV POETRY_VERSION 1.4.1

# Install system dependencies
RUN pip install "poetry==$POETRY_VERSION"

# Set work directory
WORKDIR /app

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=${OPENAI_API_KEY}

# Copy only requirements to cache them in docker layer
COPY ./backend /app/

# Disable the creation of virtual environments
RUN echo OPENAI_API_KEY=${OPENAI_API_KEY} > /app/.env && \
    cd /app && \
    poetry config virtualenvs.create false && \
    poetry install

EXPOSE 7001

RUN ["poetry", "run", "uvicorn",  "main:app", "--host",  "0.0.0.0", "--port", "7001"]

